### ISSUE TITLE
Create proper dockerization of this component

### ISSUE THREAD

**Issue by jason-fox** [ramp-eu/AGILPLAS#1]
https://github.com/ramp-eu/AGILPLAS/tree/master/docker still holds the original dummy dockerization files - please amend and dockerize your ROSE-AP as appropriate.  

Ideally the image can be placed onto Docker Hub at some point so that 6193e6f can be reverted.

**Comment by jaclavijo** [comment]
ROSE-AP is dockerized now and an image is available on Docker Hub 47c59cd1d17f396f105ab66d5ed553b6af6439c0
